### ISSUE TITLE
텍스트박스의 스크롤바에 크기에 제한이 있으면 어떨까요

### ISSUE THREAD

**Issue by grjsm99** [yunitto/chrome-KoreanWordCount#10]
![image](https://user-images.githubusercontent.com/44054161/49533459-5b312b80-f902-11e8-94d1-a0ea7cac8337.png)

텍스트를 직접입력해 줄을 늘리다보면 텍스트박스의 크기 제한이 없어서 그런지 바깥에 있는 스크롤바대신 바깥스크롤바가 대신 늘어납니다.
크기 제한을걸어 안쪽의 스크롤바를 제대로 동작하게하면 바깥 스크롤바 기능은 없어도 될거같아요.

**Comment by yunitto** [comment]
@grjsm99 감사합니다 👍
